language: java
jdk:
  - oraclejdk8
  
script: find {src/main/java/com/heroku/demo/} -name "*.java"  -print0 | xargs -0 -n1 -P8 java -cp

after script:
notification:
  recipients:
  - augusto.berwaldt@gmail.com
